version: '3.8'

services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
       test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
       interval: 10s
       timeout: 5s
       retries: 5
    volumes:
      - pg_volume:/var/lib/postgresql/data

  app:
    image: simple-etl:latest
    ports:
      - "5080:5080"

    depends_on:
      - db
    env_file:
      - .env
    command: ["python", "main.py"]

volumes:
  pg_volume:
